name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Test
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        go: ["1.24.7", "1.25.1"]

    steps:
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.go }}

      - name: Code checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: go mod download
        env:
          CGO_ENABLED: 0
        run: |
          go mod download

      - name: go test
        env:
          CGO_ENABLED: 0
        run: |
          go test ./...

      - name: go test -race
        env:
          CGO_ENABLED: 1
        run: |
          go test -race ./...
